### ISSUE TITLE
Feature: only certain types of waste

### ISSUE THREAD

**Issue by sdebruyn** [BrechtSerckx/recycle#9]
Since our "restafval", paper and "PMD" can be put in automatic containers, we only have to be alerted when they come to collect glass or "GFT". It would be helpful to only get notifications for those types of waste.

**Comment by BrechtSerckx** [comment]
@sdebruyn I've issued a fix that allows you to select the fractions for which you want to receive events. I'll try to remember to update my server tomorrow.

**Comment by BrechtSerckx** [comment]
@sdebruyn A bit of delay, but fraction filtering is supported now on my instance at recycle.brechtserckx.be

**Comment by sdebruyn** [comment]
I don't see where I can select the fractions

**Comment by BrechtSerckx** [comment]
@sdebruyn There is a `Filter` section on https://recycle.brechtserckx.be/index.html. The different fractions will be available once the address is filled in completely.

(this is because fractions are available based on your address)
